Day 10/Models/Student.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Day_10.Validators;
using Microsoft.AspNetCore.Mvc;

namespace Day_10.Models
{
	public class Student
	{
		[Key]
		public int  Id { get; set; }
		[DisplayName("Name")]
		[MinLength(3, ErrorMessage = "Name cannot be less than 3 chars ")]
		[MaxLength(23,ErrorMessage ="Name cannot exceed 23 chars ")]
		[Unique]
		public string name { get; set; }
        [DisplayName("Age")]
		//[Range(3,22)]
		[Remote("TestAge", "Student", ErrorMessage ="Age must be between 3 and 25")]
        public int age { get; set; }
        [DisplayName("Parent's Number")]
		//[RegularExpression("{010|011|012}")]
		public int parentNum { get; set; }
        [DisplayName("Image")]
        public string? image { get; set; }
		[ForeignKey("Department")]
		public int? dept_id { get; set; }
		public Department? Department { get; set; }

		public ICollection<crsResult> crsResults { get; set; } = new List<crsResult>();


	}
}

Day 10/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Day_10.Context;
using Day_10.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Day_10.Controllers
{
    public class StudentController : Controller
    {
        SchoolContext db = new SchoolContext();

        public IActionResult Delete(int id)
        {
            var st = db.Students.Find(id);
            db.Students.Remove(st);
            db.SaveChanges();
            return RedirectToAction("GetAll");


        }

        public IActionResult Edit(int id)
        {
            var st = db.Students.Include(x=>x.Department).FirstOrDefault(x => x.Id == id);
            var depts = db.Departments.ToList();
            ViewBag.depts = depts;
            return View(st);

        }
        [HttpPost]
        public IActionResult saveEdit(Student s)
        {
            if(ModelState.IsValid)
            {
                db.Students.Update(s);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            var st = db.Students.Include(x => x.Department).FirstOrDefault(x => x.Id == s.Id);
            var depts = db.Departments.ToList();
            ViewBag.depts = depts;
            return View("Edit");
        }


        [HttpGet]
        public IActionResult New(Student? s)
        {
            var depts = db.Departments.ToList();
            ViewBag.depts = depts;
            return View(s);

        }
        [HttpPost]
        public IActionResult SaveNew(Student stu)
        {
            if(ModelState.IsValid)
            {
                db.Students.Add(stu);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            var depts = db.Departments.ToList();
            ViewBag.depts = depts;
            return View("New",stu);


        }


        [Route("/Student/GetAll")]
        public IActionResult GetAll()
        {
            var stus = db.Students.ToList();
            return View(stus);
        }

        public IActionResult Details(int id)
        {
            var emp = db.Students.Include(d => d.Department).FirstOrDefault(s => s.Id == id);
            return View(emp);
        }

        public IActionResult TestAge(int age)
        {
            if(age > 3 && age < 25)
            {
                return Json(true);
            }
            return Json(false);
        }
    }
}

Day 10/Controllers/crsResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Day_10.Context;
using Day_10.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Day_10.Controllers
{
    public class crsResultController : Controller
    {
        SchoolContext db = new SchoolContext();

        [HttpGet]
        public IActionResult New(crsResult? cr)
        {
            var crs = db.Courses.ToList();
            ViewBag.crs = crs;
            var stus = db.Students.ToList();
            ViewBag.stus = stus;
            return View(cr);

        }
        [HttpPost]
        public IActionResult SaveNew(crsResult cr)
        {
            if (ModelState.IsValid)
            {
                db.crsResults.Add(cr);
                db.SaveChanges();
                return RedirectToAction("GetAll","Student");
            }
            var crs = db.Courses.ToList();
            ViewBag.crs = crs;
            var stus = db.Students.ToList();
            ViewBag.stus = stus;
            return View("New", cr);


        }
    }
}

Day 10/Views/Student/Details.cshtml
@model Student

<div class="card" style="width: 18rem;">
    <img src="/Images/@Model.image" class="card-img-top" alt=".x..">
    <div class="card-body">
        <h5 class="card-title">@Model?.name</h5>
        <p class="card-text">@Model?.Department?.name</p>
        @*<a href="/Student/GetAll" class="btn btn-primary">Go Back</a>*@
        @Html.ActionLink("Back", "GetAll", "Student", new { id = Model.Id }, new { @class = "btn btn-primary" })
        @Html.ActionLink("Add Course", "New", "crsResult", new { id = Model.Id }, new { @class = "btn btn-primary" })

    </div>
</div>

Day 10/Views/Student/Edit.cshtml
@model Student
@{

    SelectList deptOptions = new SelectList(ViewBag.depts, "Id", "name");
}
<form method="post" action="/Student/saveEdit">
    <input type="hidden" name="Id" value="@Model.Id" />
    <div class="form-group">
        @*@Html.LabelFor(s=>s.name)*@
        @*@Html.TextBoxFor(s => s.name, new {style = "color:red",@class="form-control"})*@
        <label asp-for="name"></label>
        <input asp-for="name" class="form-control" />
        <span asp-validation-for="name" style="color:rebeccapurple"></span>
    </div>
    <div class="form-group">
        <label asp-for="age"></label>
        <input asp-for="age" class="form-control" />
        <span asp-validation-for="age" style="color:rebeccapurple"></span>

    </div>
    <div class="form-group">
        <label asp-for="parentNum"></label>
        <input asp-for="parentNum" class="form-control" />
        <span asp-validation-for="parentNum" style="color:rebeccapurple"></span>

    </div>
    <div class="form-group">
        <label asp-for="image"></label>
        <input asp-for="image" class="form-control" />
        <span asp-validation-for="image" style="color:rebeccapurple"></span>

    </div>
    <div class="form-group">
        <label asp-for="Department"></label>
        @*<input type="text" name="DeptId" value="@Model?.dept_id" class="form-control">*@
        <select name="dept_id" class="form-control" asp-items="deptOptions">
            @*@foreach (Department d in ViewBag.depts)
                {
                    <option value="@d.Id">@d.name</option>
                }*@
        </select>
        <span asp-validation-for="Department" style="color:rebeccapurple"></span>

    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
@section Scripts{
    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

}

Day 10/Views/Student/GetAll.cshtml
@model List<Student>

<a asp-action ="New" asp-controller="Student" class="btn btn-outline-primary">New</a>
<br/>
<br/>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Age</th>
            <th scope="col">Grade</th>
            <th scope="col">Parent Number</th>
            <th scope="col">Image</th>


        </tr>
    </thead>
    @foreach (var m in Model)
        {
    <tbody>
        <tr>
            <td>@m.Id</td>
            <td>@m.name</td>
            <td>@m.age</td>
            @*<td>@m.grade</td>*@
            <td>@m.parentNum</td>
            <td>@m.image</td>
            <td><a asp-controller="Student" asp-action ="Details" asp-route-id="@m.Id" asp-route-name="@m.name" class="btn btn-outline-info">Details</a></td>
            <td><a asp-controller="Student" asp-action="Edit" asp-route-id="@m.Id"  class="btn btn-outline-dark">Edit</a></td>
            <td>
                <form method="post" asp-controller="Student" asp-action="Delete" style="display:inline;">
                    <input type="hidden" name="id" value="@m.Id" />
                    <button type="submit" class="btn btn-outline-danger" onclick="return confirm('Are you sure you want to delete this Student?');">
                        Delete
                    </button>
                </form>
            </td>
            <td></td>
        </tr>

    </tbody>
       }
</table>

Day 10/Views/Student/New.cshtml
@model Student
@{

    SelectList deptOptions = new SelectList(ViewBag.depts, "Id", "name");
}
<form method="post" action="/Student/saveNew">
    <div class="form-group">
        @*@Html.LabelFor(s=>s.name)*@
        @*@Html.TextBoxFor(s => s.name, new {style = "color:red",@class="form-control"})*@
        <label asp-for="name"></label>
        <input asp-for="name" class="form-control" />
        <span asp-validation-for="name" style="color:rebeccapurple"></span>
    </div>
    <div class="form-group">
        <label asp-for="age"></label>
        <input asp-for="age" class="form-control" />
        <span asp-validation-for="age" style="color:rebeccapurple"></span>

    </div>
    <div class="form-group">
        <label asp-for="parentNum"></label>
        <input asp-for="parentNum" class="form-control" />
        <span asp-validation-for="parentNum" style="color:rebeccapurple"></span>

    </div>
    <div class="form-group">
        <label asp-for="image"></label>
        <input asp-for="image" class="form-control" />
        <span asp-validation-for="image" style="color:rebeccapurple"></span>

    </div>
    <div class="form-group">
        <label asp-for="Department"></label>
        @*<input type="text" name="DeptId" value="@Model?.dept_id" class="form-control">*@
        <select name="dept_id" class="form-control" asp-items="deptOptions">
            @*@foreach (Department d in ViewBag.depts)
                {
                    <option value="@d.Id">@d.name</option>
                }*@
        </select>
        <span asp-validation-for="Department" style="color:rebeccapurple"></span>

    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts{
    <script src ="/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

}