Day 10/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Day_10.Context;
using Day_10.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Day_10.Controllers
{
    public class CourseController : Controller
    {
        SchoolContext db = new SchoolContext();

        public IActionResult Delete(int id)
        {
            var c = db.Courses.Find(id);
            db.Courses.Remove(c);
            db.SaveChanges();
            return RedirectToAction("GetAll");


        }

        public IActionResult Edit(int id)
        {
            var st = db.Courses.Include(x => x.Department).FirstOrDefault(x => x.Id == id);
            var depts = db.Departments.ToList();
            ViewBag.depts = depts;
            return View(st);

        }
        [HttpPost]
        public IActionResult saveEdit(Course c)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Update(c);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            var st = db.Courses.Include(x => x.Department).FirstOrDefault(x => x.Id == c.Id);
            var depts = db.Departments.ToList();
            ViewBag.depts = depts;
            return View("Edit");
        }


        [HttpGet]
        public IActionResult New(Course? s)
        {
            var depts = db.Departments.ToList();
            ViewBag.depts = depts;
            return View(s);

        }
        [HttpPost]
        public IActionResult SaveNew(Course stu)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(stu);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            var depts = db.Departments.ToList();
            ViewBag.depts = depts;
            return View("New", stu);


        }


        [Route("/Course/GetAll")]
        public IActionResult GetAll()
        {
            var stus = db.Courses.ToList();
            return View(stus);
        }

        public IActionResult Details(int id)
        {
            var emp = db.Courses.Include(d => d.Department).FirstOrDefault(s => s.Id == id);
            return View(emp);
        }
    }
}

Day 10/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Day_10.Context;
using Day_10.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Day_10.Controllers
{
    public class DepartmentController : Controller
    {
        SchoolContext db = new SchoolContext();

        public IActionResult Delete(int id)
        {
            var d = db.Departments.Find(id);
            db.Departments.Remove(d);
            db.SaveChanges();
            return RedirectToAction("GetAll");


        }

        public IActionResult Edit()
        {
            return View();

        }
        [HttpPost]
        public IActionResult saveEdit(Department s)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Update(s);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            return View("Edit");
        }


        [HttpGet]
        public IActionResult New(Department? s)
        {
            return View(s);

        }
        [HttpPost]
        public IActionResult SaveNew(Department d)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Add(d);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }

            return View("New", d);


        }


        [Route("/Department/GetAll")]
        public IActionResult GetAll()
        {
            var d = db.Departments.ToList();
            return View(d);
        }

        public IActionResult Details(int id)
        {
            var d = db.Departments.FirstOrDefault(s => s.Id == id);
            return View(d);
        }
    }
}

Day 10/Controllers/InstructorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Day_10.Context;
using Day_10.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Day_10.Controllers
{
    public class InstructorController : Controller
    {
        // GET: /<controller>/
        SchoolContext db = new SchoolContext();

        public IActionResult Delete(int id)
        {
            var i = db.Instructors.Find(id);
            db.Instructors.Remove(i);
            db.SaveChanges();
            return RedirectToAction("GetAll");


        }

        public IActionResult Edit(int id)
        {
            var st = db.Instructors.Include(x => x.Department).FirstOrDefault(x => x.Id == id);
            var depts = db.Departments.ToList();
            ViewBag.depts = depts;
            return View(st);

        }
        [HttpPost]
        public IActionResult saveEdit(Instructor i)
        {
            if (ModelState.IsValid)
            {
                db.Instructors.Update(i);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            return View("Edit");
        }


        [HttpGet]
        public IActionResult New(Instructor? s)
        {
            var depts = db.Departments.ToList();
            ViewBag.depts = depts;

            return View(s);

        }
        [HttpPost]
        public IActionResult SaveNew(Instructor i)
        {
            if (ModelState.IsValid)
            {
                db.Instructors.Add(i);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            return View("New", i);


        }


        public IActionResult GetAll()
        {
            var instructors = db.Instructors.ToList();
            if (instructors != null) 
                return View(instructors);
            return View("Error");
        }

        public IActionResult Details(int id)
        {
            return View(db.Instructors.Find(id));
            
        }
    }
}

Day 10/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Day_10.Context;
using Day_10.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Day_10.Controllers
{
    public class StudentController : Controller
    {
        SchoolContext db = new SchoolContext();

        public IActionResult Delete(int id)
        {
            var st = db.Students.Find(id);
            db.Students.Remove(st);
            db.SaveChanges();
            return RedirectToAction("GetAll");


        }

        public IActionResult Edit(int id)
        {
            var st = db.Students.Include(x=>x.Department).FirstOrDefault(x => x.Id == id);
            var depts = db.Departments.ToList();
            ViewBag.depts = depts;
            return View(st);

        }
        [HttpPost]
        public IActionResult saveEdit(Student s)
        {
            if(ModelState.IsValid)
            {
                db.Students.Update(s);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            var st = db.Students.Include(x => x.Department).FirstOrDefault(x => x.Id == s.Id);
            var depts = db.Departments.ToList();
            ViewBag.depts = depts;
            return View("Edit");
        }


        [HttpGet]
        public IActionResult New(Student? s)
        {
            var depts = db.Departments.ToList();
            ViewBag.depts = depts;
            return View(s);

        }
        [HttpPost]
        public IActionResult SaveNew(Student stu)
        {
            if(ModelState.IsValid)
            {
                db.Students.Add(stu);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            var depts = db.Departments.ToList();
            ViewBag.depts = depts;
            return View("New",stu);


        }


        [Route("/Student/GetAll")]
        public IActionResult GetAll()
        {
            var stus = db.Students.ToList();
            return View(stus);
        }

        public IActionResult Details(int id)
        {
            var emp = db.Students.Include(d => d.Department).FirstOrDefault(s => s.Id == id);
            return View(emp);
        }

        public IActionResult TestAge(int age)
        {
            if(age > 3 && age < 25)
            {
                return Json(true);
            }
            return Json(false);
        }
    }
}

Day 10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Day_10</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Day_10.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Home">Day_10</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="GetAll">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="GetAll">Instructor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Day_10 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Day 10/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>MarMar's School</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Simple line icons-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" rel="stylesheet" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/css/styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>
<body id="page-top">
    <!-- Header-->
    <header class="masthead d-flex align-items-center">
        <div class="container px-4 px-lg-5 text-center">
            <h1 class="mb-1">MarMar's</h1>
            <h3 class="mb-5"><em>School</em></h3>
            <a class="btn btn-primary btn-xl" href="#about">Find Out More</a>
        </div>
    </header>
    <!-- About-->
    <section class="content-section bg-light" id="about">
        <div class="container px-4 px-lg-5 text-center">
            @RenderBody()
        </div>
    </section>
    <!-- Services-->
    <section class="content-section bg-primary text-white text-center" id="services">
        <div class="container px-4 px-lg-5">
            <div class="content-section-heading">
                <h3 class="text-secondary mb-0">Services</h3>
                <h2 class="mb-5">What We Offer</h2>
            </div>
            <div class="row gx-4 gx-lg-5">
                <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                    <a asp-action="GetAll" asp-controller="Student" class="btn btn-light w-100 h-100 d-flex flex-column align-items-center p-4 rounded text-decoration-none text-dark">
                        <span class="service-icon rounded-circle mb-3"><i class="glyphicon glyphicon-user"></i></span>
                        <h4><strong>Students</strong></h4>
                    </a>
                </div>
                <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                    <a asp-action="GetAll" asp-controller="Instructor" class="btn btn-light w-100 h-100 d-flex flex-column align-items-center p-4 rounded text-decoration-none text-dark">
                        <span class="service-icon rounded-circle mb-3"><i class="glyphicon glyphicon-briefcase"></i></span>
                        <h4><strong>Instructors</strong></h4>
                    </a>
                </div>
                <div class="col-lg-3 col-md-6 mb-5 mb-md-0">
                    <a asp-action="GetAll" asp-controller="Department" class="btn btn-light w-100 h-100 d-flex flex-column align-items-center p-4 rounded text-decoration-none text-dark">
                        <span class="service-icon rounded-circle mb-3"><i class="glyphicon glyphicon-home"></i></span>
                        <h4><strong>Departments</strong></h4>
                    </a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <a asp-action="GetAll" asp-controller="Course" class="btn btn-light w-100 h-100 d-flex flex-column align-items-center p-4 rounded text-decoration-none text-dark">
                        <span class="service-icon rounded-circle mb-3"><i class="glyphicon glyphicon-book"></i></span>
                        <h4><strong>Courses</strong></h4>
                    </a>
                </div>
            </div>
        </div>
    </section>
    
    <!-- Map-->
    <div class="map" id="contact">
        <iframe src="https://www.google.com/maps/embed?pb=!1m13!1m8!1m3!1d13817.992506599681!2d31.705748!3d30.022564000000003!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zMzDCsDAxJzIxLjIiTiAzMcKwNDInMjAuNyJF!5e0!3m2!1sen!2sus!4v1725016131000!5m2!1sen!2sus"
                width="600"
                height="450"
                style="border:0;"
                allowfullscreen=""
                loading="lazy"
                referrerpolicy="no-referrer-when-downgrade">
        </iframe>
        <br />
        <small>
            <a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=New+Location+Name&amp;ie=UTF8&amp;t=m&amp;z=15&amp;iwloc=A">
                View Larger Map
            </a>
        </small>
    </div>
    <!-- Footer-->
    <footer class="footer text-center">
        <div class="container px-4 px-lg-5">
            <ul class="list-inline mb-5">
                <li class="list-inline-item">
                    <a class="social-link rounded-circle text-white mr-3" href="https://www.facebook.com/ITI.eg/?locale=ar_AR"><i class="icon-social-facebook"></i></a>
                </li>
                <li class="list-inline-item">
                    <a class="social-link rounded-circle text-white mr-3" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="icon-social-linkedin"></i></a>
                </li>
            </ul>
            <p class="text-muted small mb-0">Copyright &copy; MarMar 2024</p>
        </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top"><i class="fas fa-angle-up"></i></a>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>
</html>
@RenderSection("Scripts", false)